#
# Pull from GitHub source repository
#
stages:
  - pre
  - pull
  - test

default:
  tags:
    - docker
  image: 
    name: alpine/git
    entrypoint: [""]

pre:
  stage: pre
  script:
    - echo "Request $CI_PIPELINE_SOURCE"
    - echo "Commit  $CI_COMMIT_MESSAGE"
    - echo "Ref     $CI_COMMIT_REF_NAME"
    - echo "For     $GITLAB_USER_NAME"

abaplint:
  stage: test
  image: abaplint/abaplint:latest
  only:
    - /^issue_.*$/
    - manual
    - web
  only:
    changes:
      - "src"
  except:
    - schedules
  script:
  # - git config --global http.sslVerify false
    - git config http.sslCAInfo /certs/sap.internal.pem
    - abaplint

do-pull:
  stage: pull
  # when: manual
  only:
    - schedules
    - manual
  script:
    #   - set -x
    - git config user.email "github@redwood.com"
    - git config user.name "github"
    - git config http.sslverify false
    - git remote set-url --push origin "${TOKEN_URL_PUSH}"
    - git remote add source "${URL_SOURCE}"
    #   - git remote -v
    - git pull source master
    - git push origin HEAD:master
    - git remote rm source
    - git log -5 --oneline
